# Site settings
title: Turingnianos
email: turingnianos@gmail.com
description: "Ideas y curiosidades de informática y matemáticas"
logo_location: "logo.png"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "turingnianos.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
